apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAFPexDhTZehjvocBfF5/nFtzSQy4tbALflNJ5RRq0yRUxNTLsjQJfzXX+LPXNFDz2AWXY3zqmRmXiwN0X9RXl4/3jnFY8QdZ1FCx/W1BWZ9BZKolfjqM6+WAQZU3LIum+2QjxmhAcYW5Cz4WHWJHl50OPIbm5z7byYF98tw4k8OmIitVCb+uF3izNWZNCaWmB1sLTagxK6sn2oD5J9CPMeyC0ZiCoOSpoUYzmXAclOSYd7wLbvPXv8XMdvw6dPgGuMOvDNEyiSqcSRWw4IUdAcftFNxuIHL8GmNLMr+qdmTAN4mOK79jg/CK5ZpGNTJ1r1GBuMIADKbTbuBpG78S3nswCuNIgCFXvECmDLuSl+VJ/vglGRxDaBFMs8+pIRAxHHUXK1QPgB9OAjXirvN0EYiAld8d7AtAFnMju+1RcUj5HfuDI9jutTPz4pH/OThJu9yllPajeZs4hhNI2Ge6V2r6J3mtit1fayGEh1uq3F/vzre9h1tw2XycfL3qfpvqPm1rzmvDJ4grwvfBXXPiGlvhalXDPzFdfOWtuuwA5iKMGPO3ZISG67ZWrQSaWRWwAQQca/yeT0+f7w+IjNhXsXWk/14A5Pzr5LhsH4RcOsFA6TO8cmeFNUNq/kb8pV4HNxuY+7SUxO6KMhaGIM5ThJanpLFyQsp6lcaWDtqnyOzW7DN19WYRqqXRiM40qMxU6ZLrsnrz4ssw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

